### PR TITLE
Possible fix for benley/bazel_rules_pex#65

### PR DESCRIPTION
**Pull request by flaub**
This is an attempt to workaround benley/bazel_rules_pex#65.

It appears that under bazel 0.10, the prelude is leaking and causing consumers to have an error like:

```
every rule of type pex_binary implicitly depends upon the target '@io_bazel_rules_pex//pex:pex_wrapper', but this target could not be found because of: error loading package '@io_bazel_rules_pex//pex': Extension file not found. Unable to load package for '//pex:pex_rules.bzl': BUILD file not found on package path
```

It's unclear if this is a bazel bug in 0.10, but removing the prelude appears to workaround the issue.

### CODE REVIEW

**Comment by georgeliaw** [comment]
@benley you mind taking a look? ran into this issue as well earlier

**Comment by qzmfranklin** [comment]
@benley , I have the same issue. Would like to see it resolved soon. Thanks!

**Comment by qzmfranklin** [comment]
@benley ping again

**Comment by benley** [comment]
pong!  Sorry I haven't been able to spend much time on this project recently - I will do my best to review and merge this and various other PRs very soon.

**Pull request merged**
